name: Deploy-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  setup-webserver:
    name: Install apache2
    runs-on: ubuntu-latest
    
    steps:
      - name: install apache2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_SSH_KEY }}
          port: 22
          script: |
            apt update
            apt install apache2 -y

  setup-php:
    needs: setup-webserver
    name: install php
    runs-on: ubuntu-latest

    steps:
      - name: install php
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_SSH_KEY }}
          port: 22
          script: |
            apt install php
            apt -y install libapache2-mod-php php-mysql  
            systemctl restart apache2        

  
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    needs: setup-php
  
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_FOLDER }}

      
